stages:
  - build
  - deploy

image: moreillon/ci-dind
services:
  - name: docker:19.03.12-dind

variables:
  APPLICATION_NAME: mosquitto-auth-gateway
  CONTAINER_TAG: ${CI_COMMIT_SHORT_SHA}
  CONTAINER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CONTAINER_TAG}

build:
  stage: build
  tags:
    - dind
  before_script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAGGED}
    - docker image rm ${CONTAINER_IMAGE}

deploy:
  only:
    - master
  stage: deploy
  tags:
    - dind
  before_script:
    - kubectl config use-context moreillon_ci/moreillon_k8s/kubernetes-agent:cloud
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -n ${KUBERNETES_NAMESPACE} -f -
