apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
      - name: ${APPLICATION_NAME}
        image: ${DOCKER_IMAGE}
        # Pull new image on restart
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # Get environment variables from secret
        envFrom:
        - secretRef:
           name: environment
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  type: ClusterIP
  selector:
    app: ${APPLICATION_NAME}
  ports:
  - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${APPLICATION_NAME}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # connect to the certificate issuer
spec:
  tls:
  - hosts:
    - auth.mqtt.iot.maximemoreillon.com
    secretName: ${APPLICATION_NAME}
  rules:
  - host: auth.mqtt.iot.maximemoreillon.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ${APPLICATION_NAME}
          servicePort: 80
